#ifndef SERIALISABLES_HPP_INCLUDED
#define SERIALISABLES_HPP_INCLUDED

#include <networking/serialisable_fwd.hpp>

DECLARE_SERIALISE_FUNCTION(component);
DECLARE_SERIALISE_FUNCTION(ship);
DECLARE_SERIALISE_FUNCTION(aoe_damage);
DECLARE_SERIALISE_FUNCTION(radar_object);
DECLARE_SERIALISE_FUNCTION(alt_radar_sample);
DECLARE_SERIALISE_FUNCTION(common_renderable);
DECLARE_SERIALISE_FUNCTION(build_in_progress);
DECLARE_SERIALISE_FUNCTION(player_research);
DECLARE_SERIALISE_FUNCTION(blueprint_node);
DECLARE_SERIALISE_FUNCTION(blueprint);
DECLARE_SERIALISE_FUNCTION(blueprint_manager);

DECLARE_SERIALISE_FUNCTION(player_model);
DECLARE_SERIALISE_FUNCTION(persistent_user_data);
DECLARE_SERIALISE_FUNCTION(auth_data);
DECLARE_SERIALISE_FUNCTION(system_descriptor);
DECLARE_SERIALISE_FUNCTION(client_entities);
DECLARE_SERIALISE_FUNCTION(client_fire);
DECLARE_SERIALISE_FUNCTION(warp_info);
DECLARE_SERIALISE_FUNCTION(poi_travel_info);
DECLARE_SERIALISE_FUNCTION(client_room_object_data);
DECLARE_SERIALISE_FUNCTION(client_input);

#endif // SERIALISABLES_HPP_INCLUDED
